// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etkizhbvusbnqkzmngbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0a2l6aGJ2dXNibnFrem1uZ2JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3MzE1NTAsImV4cCI6MjA1NjMwNzU1MH0.3EODfROW5Y5Fj6In4xOKODD04XTE0Q6_xbyItz9I69A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);